#!/bin/sh
set -eu

cd "$(dirname "$0")"

GIT_ROOT=$(git rev-parse --show-toplevel)
TEMP_WD=$(mktemp -d)
trap 'rm -rf "$TEMP_WD"' EXIT

echo "Downloading the PPU Interlace test repository into $TEMP_WD ..."
cd "$TEMP_WD"
git clone https://github.com/PeterLemon/SNES .

echo "Extracting just the PPU Interlace tests..."
git branch subtree-export $(git subtree split -P PPU/Interlace HEAD)

echo "Merging the tests into our repo..."
cd "$GIT_ROOT"
git subtree pull -P PeterLemon/SNES-PPU-Interlace "$TEMP_WD" subtree-export
